# Generated by Django 6.0.6 on 2026-07-02 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics dashboard",
                "verbose_name_plural": "Analytics dashboard",
                "permissions": [("view_dashboard", "Can view the ProMetric dashboard")],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                ("provider", models.CharField(max_length=50)),
                ("period", models.CharField(max_length=10)),
                ("filters", models.JSONField(default=dict)),
                ("data", models.JSONField(default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retakes",
                        to="django_prometric.snapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "snapshot",
                "verbose_name_plural": "snapshots",
                "ordering": ["-taken_at"],
            },
        ),
    ]
