# Generated by Django 6.0.6 on 2026-07-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_prometric", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="window_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="window_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="provider",
            field=models.CharField(max_length=100),
        ),
    ]
